# Architecture 81.37%
arch: convmixer_1536_20

# ===== Dataset ===== #
data_url: ./data/imagenet
set: ImageNet
num_classes: 1000
mix_up: 0.5
cutmix: 0.5
auto_augment: rand-m9-mstd0.5-inc1
interpolation: bicubic
re_prob: 0.25
re_mode: pixel
re_count: 1
mixup_prob: 1.
switch_prob: 0.5
mixup_mode: batch
crop_pct: 0.96


# ===== Learning Rate Policy ======== #
optimizer: adamw
base_lr: 0.004
warmup_lr: 0.0001
min_lr: 0.000001
lr_scheduler: onecycle_lr
warmup_length: 0
nonlinearity: GELU


# ===== Network training config ===== #
amp_level: O1
keep_bn_fp32: True
beta: [ 0.9, 0.999 ]
clip_global_norm_value: 1.
is_dynamic_loss_scale: True
epochs: 150
label_smoothing: 0.1
loss_scale: 1024
weight_decay: 0.02
momentum: 0.9
batch_size: 32

# ===== Hardware setup ===== #
num_parallel_workers: 16
device_target: Ascend

# ===== Model config ===== #
drop_path_rate: 0.2
image_size: 224